//
//	$Id: sf_error.h,v 1.17 2006/02/28 05:52:26 ssosuny Exp $
//

#ifndef __SF_ERROR_H__
#define __SF_ERROR_H__

//
// common					[-10, ..., -99]
//
#define	SF_COMMON_ERROR_INVALID_INPUT				-10
#define	SF_COMMON_ERROR_INTERNAL					-11
#define	SF_COMMON_ERROR_MALLOC_FAILED				-12

//
// cmvp
//
#define	SF_CRYPTO_ERROR_NOT_INITIALIZED				-20
#define	SF_CRYPTO_ERROR_NOT_IMPLEMENTED				-21
#define	SF_CRYPTO_ERROR_SELFTEST_FAILED				-22

#define	SF_CRYPTO_ERROR_UNKNOWN_STATEID				-30
#define	SF_CRYPTO_ERROR_STATE_NOT_ALLOWED			-31
#define	SF_CRYPTO_ERROR_STATE_IN_ERROR				-32
#define	SF_CRYPTO_ERROR_STATE_IN_FINALIZED			-33

#define	SF_CRYPTO_ERROR_BAD_ENCBLOB					-40
#define	SF_CRYPTO_ERROR_MISMATCH_ENCBLOB			-41
#define	SF_CRYPTO_ERROR_INVALID_ENCBLOB				-42

//
// asn1
//
#define	SF_ASN1_ERROR_BAD_DATA						-80
#define	SF_ASN1_ERROR_BAD_LENGTH					-81

//
// cipher					[-100, ..., -199]
//
#define	SF_CIPHER_ERROR_UNKNOWN_ID					-100
#define	SF_CIPHER_ERROR_UNKNOWN_MODE				-101
#define	SF_CIPHER_ERROR_UNKNOWN_PADDING				-102
#define	SF_CIPHER_ERROR_INVALID_PADDING				-103
#define	SF_CIPHER_ERROR_UNSUPPORTED_ID				-104
#define	SF_CIPHER_ERROR_IV_LENGTH					-110
#define	SF_CIPHER_ERROR_MODE_SIZE					-111
#define	SF_CIPHER_ERROR_KEY_LENGTH					-112
#define	SF_CIPHER_ERROR_ENCRYPT_FAILED				-120
#define	SF_CIPHER_ERROR_DECRYPT_FAILED				-121
#define	SF_CIPHER_ERROR_LOAD_NEATLIB				-130
#define	SF_CIPHER_ERROR_LOAD_NESLIB					-131

//
// hash						[-200, ..., -299]
//
#define	SF_HASH_ERROR_UNKNOWN_ID					-200
#define	SF_HASH_ERROR_UNSUPPORTED_ID				-201

//
// mac						[-300, ..., -399]
//
#define	SF_MAC_ERROR_UNKNOWN_ID						-310
#define	SF_MAC_ERROR_UNSUPPORTED_ID					-311

#define	SF_CBCMAC_ERROR_UNKNOWN_ID					-320

//
// rand						[-400, ..., -499]
//
#define	SF_RAND_ERROR_INVALID_SEED_SEEDKEY			-410

//
// bigint	 				[-500, ..., -549]
//
#define SF_BIGINT_ERROR_GCD_IS_NOT_ONE				-500
#define	SF_BIGINT_ERROR_INPUT_TOO_LARGE				-501
#define	SF_BIGINT_ERROR_NO_SQRT						-502

//
// gf2m, ec					[-550, ... -599]
//
#define	SF_GF2M_ERROR_DEGREE_IS_EVEN				-550
#define SF_GF2M_ERROR_NO_SOLUTION					-551

#define	SF_EC_ERROR_BAD_FIELD						-570
#define	SF_EC_ERROR_BAD_CONV_FORMAT					-571
#define	SF_EC_ERROR_POINT_INFINITY					-572
#define SF_EC_ERROR_INPUT_TOO_LARGE					-573
#define	SF_EC_ERROR_NOT_IMPL_CURVE					-574

//
// rsa, dh, dsa, kcdsa, 	[-600, ..., -699]
// ecdh, ecdsa, eckcdsa
//

#define	SF_RSA_ERROR_INPUT_TOO_LARGE				-600
#define	SF_RSA_ERROR_INVALID_KEY_PAIR				-603
#define	SF_DH_ERROR_INVALID_PARAMETERS				-610
#define	SF_DH_ERROR_INVALID_PUBLIC_KEY				-612
#define	SF_DH_ERROR_INVALID_KEY_PAIR				-613
#define	SF_DSA_ERROR_INVALID_PARAMETERS				-620
#define	SF_DSA_ERROR_INVALID_PUBLIC_KEY				-622
#define	SF_DSA_ERROR_INVALID_KEY_PAIR				-623
#define	SF_DSA_ERROR_INVALID_SIGNATURE				-625
#define	SF_KCDSA_ERROR_INVALID_PARAMETERS			-630
#define	SF_KCDSA_ERROR_INVALID_PUBLIC_KEY			-632
#define	SF_KCDSA_ERROR_INVALID_KEY_PAIR				-633
#define	SF_KCDSA_ERROR_INVALID_SIGNATURE			-635
#define	SF_ECDSA_ERROR_INVALID_PUBLIC_KEY			-652
#define	SF_ECDSA_ERROR_INVALID_KEY_PAIR				-653
#define	SF_ECDSA_ERROR_INVALID_SIGNATURE			-655
#define	SF_ECKCDSA_ERROR_INVALID_PUBLIC_KEY			-662
#define	SF_ECKCDSA_ERROR_INVALID_KEY_PAIR			-663
#define SF_ECKCDSA_ERROR_INVALID_SIGNATURE			-665

//
// pkcs1					[-700, ..., -749]
//
#define	SF_PKCS1_ERROR_UNKNOWN_ID					-700
#define	SF_PKCS1_ERROR_DECODING_ERROR				-710
#define	SF_PKCS1_ERROR_DECRYPTION_ERROR				-711
#define	SF_PKCS1_ERROR_ENCODING_ERROR				-712
#define	SF_PKCS1_ERROR_INCONSISTENT					-713
#define	SF_PKCS1_ERROR_INTEGER_TOO_LARGE			-714
#define	SF_PKCS1_ERROR_INTENDED_MSG_LENGTH_TOO_SHORT	-715
#define	SF_PKCS1_ERROR_INVALID_SIGNATURE			-716
#define	SF_PKCS1_ERROR_MESSAGE_TOO_LONG				-717
#define	SF_PKCS1_ERROR_MODULUS_TOO_SHORT			-718
#define	SF_PKCS1_ERROR_PARAMETER_STRING_TOO_LONG	-719

//
// pkey						[-750, ..., -799]
//
#define	SF_PKEY_ERROR_UNKNOWN_PKEYID				-750
#define	SF_PKEY_ERROR_UNKNOWN_PENCID				-751
#define	SF_PKEY_ERROR_UNKNOWN_SIGNID				-752
#define	SF_PKEY_ERROR_UNKNOWN_MSGID					-753
#define	SF_PKEY_ERROR_UNSUPPORTED_PKEYID			-755
#define	SF_PKEY_ERROR_UNSUPPORTED_PENCID			-756
#define	SF_PKEY_ERROR_UNSUPPORTED_SIGNID			-757

#define	SF_PKEY_ERROR_INVALID_PARAMETERS			-760
#define	SF_PKEY_ERROR_INVALID_PRIVATE_KEY			-761
#define	SF_PKEY_ERROR_INVALID_PUBLIC_KEY			-762
#define	SF_PKEY_ERROR_INVALID_KEY_PAIR				-763

#endif
