//
//	suite_ssl_error.h
//

#ifndef _SUITE_SSL_ERROR_H_
#define _SUITE_SSL_ERROR_H_

#include "exp_global.h"

/**
 *	Constants
 */

#define	SSL_ERR_INVALID_INPUT					(ERR_SSL + 1)
#define	SSL_ERR_INTERNAL						(ERR_SSL + 2)
#define	SSL_ERR_MALLOC_FAILED					(ERR_SSL + 3)

#define SSL_ERR_SOCKET_READ_FAILED				(ERR_SSL + 10)
#define SSL_ERR_SOCKET_WRITE_FAILED				(ERR_SSL + 11)
#define SSL_ERR_SOCKET_CLOSED					(ERR_SSL + 12)
#define	SSL_ERR_SOCKET_READ_WAIT				(ERR_SSL + 13)
#define	SSL_ERR_SOCKET_WRITE_WAIT				(ERR_SSL + 14)

#define	SSL_ERR_UNKNOWN_STATE					(ERR_SSL + 20)
#define	SSL_ERR_UNKNOWN_CIPHER					(ERR_SSL + 21)
#define	SSL_ERR_UNKNOWN_HASH					(ERR_SSL + 22)
#define	SSL_ERR_UNKNOWN_SIGN_TYPE				(ERR_SSL + 23)
#define	SSL_ERR_UNKNOWN_CIPHER_SUITES			(ERR_SSL + 24)

#define	SSL_ERR_BAD_LENGTH						(ERR_SSL + 30)
#define	SSL_ERR_BAD_PROTOCOL_VERSION			(ERR_SSL + 31)
#define	SSL_ERR_BAD_CERT						(ERR_SSL + 32)

#define	SSL_ERR_NO_CIPHER_SUITES				(ERR_SSL + 60)
#define	SSL_ERR_NO_COMPRESSION_METHODS			(ERR_SSL + 61)
#define	SSL_ERR_NO_CIPHER_SUITE_MATCH			(ERR_SSL + 62)
#define	SSL_ERR_NO_COMPRESSION_METHOD_MATCH		(ERR_SSL + 63)
#define	SSL_ERR_NO_SELF_CERTIFICATE				(ERR_SSL + 64)
#define	SSL_ERR_NO_PEER_CERTIFICATE				(ERR_SSL + 65)

#define SSL_ERR_CLOSE_NOTIFY 					(ERR_SSL + 100 + 0)
#define SSL_ERR_UNEXPECTED_MESSAGE 				(ERR_SSL + 100 + 10)
#define SSL_ERR_BAD_RECORD_MAC					(ERR_SSL + 100 + 20)
#define SSL_ERR_DECOMPRESSION_FAILURE			(ERR_SSL + 100 + 30)
#define SSL_ERR_HANDSHAKE_FAILURE				(ERR_SSL + 100 + 40)
#define SSL_ERR_NO_CERTIFICATE					(ERR_SSL + 100 + 41)
#define SSL_ERR_BAD_CERTIFICATE					(ERR_SSL + 100 + 42)
#define SSL_ERR_UNSUPPORTED_CERTIFICATE			(ERR_SSL + 100 + 43)
#define SSL_ERR_CERTIFICATE_REVOKED				(ERR_SSL + 100 + 44)
#define SSL_ERR_CERTIFICATE_EXPIRED				(ERR_SSL + 100 + 45)
#define SSL_ERR_CERTIFICATE_UNKNOWN				(ERR_SSL + 100 + 46)
#define SSL_ERR_ILLEGAL_PARAMETER				(ERR_SSL + 100 + 47)

#define	SSL_ERR_ALERT_RECV						(ERR_SSL + 150)
#define	SSL_ERR_ALERT_SENT						(ERR_SSL + 151)

#define	SSL_ERR_RECORD_ENCRYPT_FAILED			(ERR_SSL + 160)
#define	SSL_ERR_RECORD_DECRYPT_FAILED			(ERR_SSL + 161)

#define	SSL_ERR_CRYPTO_LIB						(ERR_SSL + 170)
#define	SSL_ERR_PKCS1_LIB						(ERR_SSL + 171)

#define	SSL_ERR_NO_CALLBACK						(ERR_SSL + 200)
#define	SSL_ERR_CERTCB_VERIFYCERTIFICATE		(ERR_SSL + 201)
#define	SSL_ERR_CERTCB_GETSELFCERTIFICATE		(ERR_SSL + 202)
#define	SSL_ERR_CERTCB_GETURLCERTIFICATE		(ERR_SSL + 203)
#define	SSL_ERR_CERTCB_COMPUTESIGNATURE			(ERR_SSL + 204)
#define	SSL_ERR_CERTCB_VERIFYSIGNATURE			(ERR_SSL + 205)
#define	SSL_ERR_CERTCB_ENCRYPTMESSAGE			(ERR_SSL + 206)
#define	SSL_ERR_CERTCB_DECRYPTMESSAGE			(ERR_SSL + 207)
#define	SSL_ERR_CERTCB_GETCADNLIST				(ERR_SSL + 208)
#define	SSL_ERR_SESSIONCB_CREATESESSION			(ERR_SSL + 209)
#define	SSL_ERR_SESSIONCB_READSESSION			(ERR_SSL + 210)
#define	SSL_ERR_SESSIONCB_WRITESESSION			(ERR_SSL + 211)
#define	SSL_ERR_SESSIONCB_DELETESESSION			(ERR_SSL + 212)
#define	SSL_ERR_TEMPKEYCB_GETKEYPAIR			(ERR_SSL + 215)
#define	SSL_ERR_TEMPKEYCB_GETRANDOM				(ERR_SSL + 217)

/**
 *	Prototypes
 */

#ifdef  __cplusplus
extern "C" {
#endif

XFA_EXPORT_TYPE
char *	XFA_SSL_GetErrorReason				(const int code, 
											 const int locale);

#ifdef  __cplusplus
}
#endif

#endif
